roboptim::trajectory::detail Namespace Reference
roboptim::trajectory::detail Namespace Reference
Classes
struct ComputeIntegral
Functions
Function::value_type unscaleTime (Function::value_type unscaled, Function::value_type min, Function::value_type scale)
template<unsigned dorder>
Function::interval_t unscaleInterval (const Trajectory< dorder > &traj, typename Function::value_type scale)
std::string getLimitSpeedName (const StableTimePoint &timePoint)
template<typename T >
double fixTime (double t, const T &trajectory)
Function Documentation
template<typename T > double roboptim::trajectory::detail::fixTime (double t, const T & trajectory)
Referenced by roboptim::trajectory::ConstrainedBSpline< N >::addCoupledConstraint(), roboptim::trajectory::ConstrainedBSpline< N >::addFixedConstraint(), roboptim::trajectory::CubicBSpline::basisFunctions(), roboptim::trajectory::BSpline< N >::basisFunctions(), roboptim::trajectory::CubicBSpline::impl_compute(), roboptim::trajectory::BSpline< N >::impl_compute(), roboptim::trajectory::CubicBSpline::impl_derivative(), roboptim::trajectory::BSpline< N >::impl_derivative(), roboptim::trajectory::BSpline< N >::interval(), roboptim::trajectory::CubicBSpline::interval(), roboptim::trajectory::FreeTimeTrajectory< T >::scaleTime(), roboptim::trajectory::FreeTimeTrajectory< T >::unscaleTime(), roboptim::trajectory::CubicBSpline::variationDerivWrtParam(), and roboptim::trajectory::BSpline< N >::variationDerivWrtParam().
std::string roboptim::trajectory::detail::getLimitSpeedName (const StableTimePoint & timePoint)
References roboptim::trajectory::StableTimePoint::getAlpha().
template<unsigned dorder> Function::interval_t roboptim::trajectory::detail::unscaleInterval (const Trajectory< dorder > & traj, typename Function::value_type scale)
References roboptim::trajectory::Trajectory< DerivabilityOrder >::timeRange(), and unscaleTime().
Referenced by roboptim::trajectory::FreeTimeTrajectory< T >::setParameters().
Function::value_type roboptim::trajectory::detail::unscaleTime (Function::value_type unscaled, Function::value_type min, Function::value_type scale) [inline]
Referenced by unscaleInterval().