sudo: required
language: cpp
env:
  global:
  - APT_DEPENDENCIES="cmake cmake-data doxygen libltdl-dev libboost-all-dev liblog4cxx10-dev"
  - HOMEBREW_DEPENDENCIES="doxygen log4cxx brewsci/science/ipopt openblas mumps"
  - GIT_DEPENDENCIES="roboptim/roboptim-core roboptim/roboptim-core-plugin-ipopt"
  - DEBSIGN_KEYID=5AE5CD75
  - PPA_URI="roboptim/ppa"
  - LCOV_IGNORE_RULES="*tests*"
  - GH_USERNAME=thomas-moulard
  - GH_REPO=roboptim/roboptim-trajectory
  - EIGEN_MAJOR=3.2
  - secure: dn2Iai0VINXoHlHTL0s0/+37pIbTTaKI0698dAPYpMBUkE9RIuumcKEjDP1uKqaA9anSPm1dLrtSsSm+kFGaEBk+cviGxsc242KSxqxCBqNP3Bbm4dFCbKnnG4c7I8OTuYUuJJg90xVm2QGAnUNn9vvBnydvTpeCEN850lT+dBM=
  - secure: qFCzChpnDkG00gsaRzNmjbWyBzEaHutoM6BUsm9jxH2BlvDRLQUN/WxVmmIKKB9t8y3d2jPp4zRJiTqTUTJo3DaUuc/5s5XZKEqmL1YgIP+UbIWJpDNaun9EpA2YJxoFatYzun6X1FKm2D7WMSVXatKyRDh1bEVaoW8tqI6Vwq0=
  - secure: GwtCk4WjcY6iyQxmVD4YQ2NkEP7H/zdBv2144UNtLe6jaLxwFsDt0n9mNIela/bCyEq2GQsjI3QofbFol5EAMhv1Dm93mLYsyWCGNcZrRN/OwfjluMcBlq5WMETbYXl/009kw3lxXWddNBHTR6QCEAlnZ9fUmj+3diy/UVvW74c=
  - secure: "FeD8bUPyJbez7IDLEoNyfyPxgpmxJ008dkwHdBl5gyUh8E9VD5XN/w/9FWIkEey7yqpMmbrHzaDjYKzMQ1pJI6jpcnkcQ9AxZSIJxjFInI99kLMfIK+RClprWtSPqyb4pe1dq2ZKKvUBuc2eyh1ZseVfxoQsU8q/rfDbSYGqRnI="
notifications:
  email: roboptim@googlegroups.com
  hipchat:
    rooms:
      secure: X+ZM9zdIE0uAXC6FcGszec+DYxgzkuNkwmDJmofwbTFFhzhoWQxu2EbvGnyBe06MVRzlfIisWBXUgln/dCxMTqbXy0jFxU5L2clQawUXQFtD17hgjeQ1ZO6wdBXqfFTbh1oWr6yKEvz1q2EE6FVEXGllejVVC4HTkynZPSFsukI=
branches:
  only:
  - master
  - dev
  - debian
  - travis
  - coverity_scan
script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export LD_LIBRARY_PATH=`pkg-config --variable=plugindir roboptim-core`:$LD_LIBRARY_PATH; fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then export DYLD_LIBRARY_PATH=`pkg-config --variable=plugindir roboptim-core`:$DYLD_LIBRARY_PATH; fi
  - if [ "${ENABLE_CXX11}" == "1" ]; then export CMAKE_ADDITIONAL_OPTIONS="-DUSE_CXX11:BOOL=ON -DROBOPTIM_PRECOMPILE_DENSE_SPARSE:BOOL=ON ${CMAKE_ADDITIONAL_OPTIONS}"; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != "1" ]; then ./.travis/run build; fi
after_success:
  - ./.travis/run after_success
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then codecov --gcov-root=/tmp/_ci/build; fi
after_failure: ./.travis/run after_failure
before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then pip install --user codecov; fi
  - ./.travis/dependencies/eigen-${EIGEN_MAJOR}
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then CC=gcc CXX=g++ ./.travis/dependencies/ipopt; fi
  - ./.travis/run before_install

matrix:
  allow_failures:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang
    - env: COVERITY_SCAN_BRANCH=1
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
      env: ENABLE_CXX11=1
    - os: linux
      dist: precise
      compiler: gcc
      env: MASTER_PPA="george-edison55/precise-backports"
    - os: linux
      dist: precise
      compiler: clang
      env: MASTER_PPA="george-edison55/precise-backports"
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  coverity_scan:
    project:
      name: "roboptim/roboptim-trajectory"
      description: "Build submitted via Travis CI"
    notification_email: roboptim@googlegroups.com
    build_command_prepend: ". .travis/common.sh && mkdir coverity && cd coverity && cmake .."
    build_command: "make"
    branch_pattern: coverity_scan
