roboptim::trajectory Namespace Reference
roboptim::trajectory Namespace Reference
Namespaces
namespace detail
namespace visualization
Classes
class AnthropomorphicCostFunction
Cost function from ``An optimal control model unifying holonomic and nonholonomic walking'' Katja Mombaur, Jean-Paul Laumond, Eiichi Yoshida (2008 8th IEEE-RAS Interational Conference on Humanoid Robots).
class BSpline
class ConstrainedBSpline
Constrained B-spline.
class ConstraintsOverSplines
Constraint function on a spline's interval.
class CubicBSpline
Cubic B-Spline trajectory.
class FreeTimeTrajectory
Decorate a trajectory to make time scalable.
class Freeze
Freeze parameters by modifying argument bounds.
class FrontalSpeed
class JerkOverSplinesFactory
Factory generating a jerk cost function over a vector of splines.
class LimitOmega
class LimitSpeed
class OrthogonalSpeed
class Polynomial
Polynomial of degree at most N (N >= 0).
struct Monomial
Monomial
\[ M (t) = t-t_0 \]
.
class ProblemOverSplinesFactory
Factory of problems over splines.
class SplineLength
Approximate the length of a Spline.
class StablePointStateFunction
Trajectory cost function defined by state evaluation at parameter.
class TMax
class StableTimePoint
class StateFunction
Trajectory cost function defined by state evaluation at parameter.
class TrajectoryCost
Meta-function for trajectory cost.
class TrajectorySumCost
Trajectory cost function defined by sum of state evaluations at parameters.
class Trajectory
Abstract trajectory.
class VectorInterpolation
Takes a vector or argument and differentiate it.
Typedefs
typedef Polynomial< 3 > Polynomial3
Polynomial of degree at most 3.
typedef Monomial< 3 > Monomial3
Monomial3
\[ M (t) = t-t_0 \]
.
Functions
Function::vector_t addScaleToParameters (Function::const_vector_ref p, Function::value_type t=1.)
Function::vector_t removeScaleFromParameters (Function::const_vector_ref v)
template<typename P >
Freeze< P > makeFreeze (P &problem)
template<int N>
std::ostream & operator<< (std::ostream &stream, const Polynomial< N > &p)
Print a polynomial to a given output stream.
template<int N>
Polynomial< N > operator* (typename Polynomial< N >::value_type lambda, const Polynomial< N > &poly)
StableTimePoint operator* (Function::value_type alpha, TMax)
StableTimePoint operator* (TMax, Function::value_type alpha)
boost::shared_ptr
< VectorInterpolation > vectorInterpolation (VectorInterpolation::vector_t x, VectorInterpolation::size_type outputSize, VectorInterpolation::value_type dt=1.)
Variables
static const TMax tMax = TMax ()
Typedef Documentation
typedef Monomial<3> roboptim::trajectory::Monomial3
Monomial3
\[ M (t) = t-t_0 \]
.
typedef Polynomial<3> roboptim::trajectory::Polynomial3
Polynomial of degree at most 3.
\[ P (t) = \sum_{i=0}^{3} a_i (t-t_0)^i \]
Function Documentation
Function::vector_t roboptim::trajectory::addScaleToParameters (Function::const_vector_ref p, Function::value_type t = 1.) [inline]
template<typename P > Freeze<P> roboptim::trajectory::makeFreeze (P & problem)
StableTimePoint roboptim::trajectory::operator* (Function::value_type alpha, TMax) [inline]
StableTimePoint roboptim::trajectory::operator* (TMax , Function::value_type alpha) [inline]
template<int N> Polynomial< N > roboptim::trajectory::operator* (typename Polynomial< N >::value_type lambda, const Polynomial< N > & poly)
template<int N> std::ostream & roboptim::trajectory::operator<< (std::ostream & stream, const Polynomial< N > & p)
Print a polynomial to a given output stream.
Template Parameters:
N polynomial degree.
Parameters:
o output stream.
p polynomial.
Returns:
output stream.
Function::vector_t roboptim::trajectory::removeScaleFromParameters (Function::const_vector_ref v) [inline]
Referenced by roboptim::trajectory::FreeTimeTrajectory< T >::setParameters().
boost::shared_ptr<VectorInterpolation> roboptim::trajectory::vectorInterpolation (VectorInterpolation::vector_t x, VectorInterpolation::size_type outputSize, VectorInterpolation::value_type dt = 1.) [inline]
Variable Documentation
const TMax roboptim::trajectory::tMax = TMax () [static]
Referenced by roboptim::trajectory::LimitOmega< T >::addToProblem(), roboptim::trajectory::LimitSpeed< T >::addToProblem(), roboptim::trajectory::StablePointStateFunction< T >::addToProblem(), roboptim::trajectory::StateFunction< T >::addToProblem(), roboptim::trajectory::visualization::gnuplot::detail::PlotLimitSpeed< T >::operator()(), roboptim::trajectory::visualization::gnuplot::plot_speeds(), roboptim::trajectory::visualization::gnuplot::plot_xy(), roboptim::trajectory::visualization::gnuplot::plot_xytheta(), roboptim::trajectory::FreeTimeTrajectory< T >::resize(), and roboptim::trajectory::FreeTimeTrajectory< T >::unscaleTime().