roboptim::trajectory::StableTimePoint Class Reference
roboptim::trajectory::StableTimePoint Class Reference
#include <roboptim/trajectory/stable-time-point.hh>
Public Types
typedef Function::value_type value_type
Public Member Functions
StableTimePoint (value_type alpha)
const value_type & getAlpha () const
value_type getTime (Function::interval_t timeRange) const
Member Typedef Documentation
typedef Function::value_type roboptim::trajectory::StableTimePoint::value_type
Constructor & Destructor Documentation
roboptim::trajectory::StableTimePoint::StableTimePoint (value_type alpha) [inline, explicit]
Member Function Documentation
const value_type& roboptim::trajectory::StableTimePoint::getAlpha () const [inline]
Referenced by roboptim::trajectory::detail::getLimitSpeedName().
value_type roboptim::trajectory::StableTimePoint::getTime (Function::interval_t timeRange) const [inline]
Referenced by roboptim::trajectory::Trajectory< DerivabilityOrder >::impl_compute(), roboptim::trajectory::VectorInterpolation::impl_derivative(), roboptim::trajectory::BSpline< N >::impl_derivative(), roboptim::trajectory::CubicBSpline::impl_derivative(), roboptim::trajectory::visualization::gnuplot::plot_speeds(), roboptim::trajectory::visualization::gnuplot::plot_xytheta(), roboptim::trajectory::CubicBSpline::variationConfigWrtParam(), roboptim::trajectory::BSpline< N >::variationConfigWrtParam(), roboptim::trajectory::VectorInterpolation::variationDerivWrtParam(), roboptim::trajectory::CubicBSpline::variationDerivWrtParam(), and roboptim::trajectory::BSpline< N >::variationDerivWrtParam().