roboptim::trajectory::visualization::matplotlib Namespace Reference
roboptim::trajectory::visualization::matplotlib Namespace Reference
Namespaces
namespace detail
Typedefs
typedef
roboptim::visualization::matplotlib::Command Command
Functions
template<int N>
Command plot_spline (const BSpline< N > &spline, typename BSpline< N >::value_type step)
Command plot_spline (const CubicBSpline &spline, CubicBSpline::value_type step)
Typedef Documentation
typedef roboptim::visualization::matplotlib::Command roboptim::trajectory::visualization::matplotlib::Command
Function Documentation
Command roboptim::trajectory::visualization::matplotlib::plot_spline (const CubicBSpline & spline, CubicBSpline::value_type step)
References roboptim::trajectory::visualization::matplotlib::detail::formattedVarName(), roboptim::trajectory::CubicBSpline::getNumberControlPoints(), roboptim::trajectory::CubicBSpline::knotVector(), roboptim::trajectory::Trajectory< DerivabilityOrder >::parameters(), roboptim::trajectory::Trajectory< DerivabilityOrder >::timeRange(), and roboptim::trajectory::CubicBSpline::toPolynomials().
template<int N> Command roboptim::trajectory::visualization::matplotlib::plot_spline (const BSpline< N > & spline, typename BSpline< N >::value_type step)
References roboptim::trajectory::visualization::matplotlib::detail::formattedVarName(), roboptim::trajectory::BSpline< N >::getNumberControlPoints(), roboptim::trajectory::BSpline< N >::knotVector(), roboptim::trajectory::Trajectory< N >::parameters(), roboptim::trajectory::Trajectory< N >::timeRange(), and roboptim::trajectory::BSpline< N >::toPolynomials().