roboptim::trajectory::visualization::gnuplot Namespace Reference
roboptim::trajectory::visualization::gnuplot Namespace Reference
Namespaces
namespace detail
Typedefs
typedef
roboptim::visualization::gnuplot::Command Command
Functions
template<unsigned dorder>
Command plot_limitSpeed (const Trajectory< dorder > &trajectory, boost::optional< double > vMax=boost::optional< double >(), typename Trajectory< dorder >::value_type step=.01)
Plot a speed limit constraint.
template<typename T >
Command plot_speeds (const T &traj, typename T::value_type step=.01)
template<unsigned N>
Command plot_xy (const Trajectory< N > &traj, typename Trajectory< N >::value_type step=.01)
Plot a 2D trajectory with Gnuplot.
template<typename T >
Command plot_xytheta (const T &traj, typename T::value_type step=.01)
Typedef Documentation
typedef roboptim::visualization::gnuplot::Command roboptim::trajectory::visualization::gnuplot::Command
Function Documentation
template<unsigned dorder> Command roboptim::trajectory::visualization::gnuplot::plot_limitSpeed (const Trajectory< dorder > & trajectory, boost::optional< double > vMax = boost::optional<double> (), typename Trajectory< dorder >::value_type step = .01)
Plot a speed limit constraint.
Returns:
Gnuplot command
Examples:
spline-time-optimization.cc.
References roboptim::trajectory::Trajectory< DerivabilityOrder >::timeRange().
template<typename T > Command roboptim::trajectory::visualization::gnuplot::plot_speeds (const T & traj, typename T::value_type step = .01)
References roboptim::trajectory::StableTimePoint::getTime(), and roboptim::trajectory::tMax.
template<unsigned N> Command roboptim::trajectory::visualization::gnuplot::plot_xy (const Trajectory< N > & traj, typename Trajectory< N >::value_type step = .01)
Plot a 2D trajectory with Gnuplot.
Plot a 2D trajectory in Gnuplot.
Parameters:
traj trajectory to be displayed
step discretization step.
Returns:
Gnuplot command
Examples:
spline-optimization.cc.
References roboptim::trajectory::Trajectory< DerivabilityOrder >::timeRange(), and roboptim::trajectory::tMax.
template<typename T > Command roboptim::trajectory::visualization::gnuplot::plot_xytheta (const T & traj, typename T::value_type step = .01)
References roboptim::trajectory::StableTimePoint::getTime(), and roboptim::trajectory::tMax.